name: fm_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2020.4.5.2
  - certifi=2020.4.5.2
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.5.0
  - libgomp=9.2.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libstdcxx-ng=9.2.0
  - ncurses=6.1
  - numpy=1.18.5
  - openssl=1.1.1g
  - pandas=1.0.5
  - pip=20.1.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2020.1
  - readline=8.0
  - setuptools=47.3.1
  - six=1.15.0
  - sqlite=3.30.1
  - tk=8.6.10
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11

